services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-dev
    restart: unless-stopped

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SqlServer#2026"
      MSSQL_PID: "Developer"

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "SqlServer#2026" -Q "SELECT 1" || exit 1
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

volumes:
  sqlserver_data: